production:
    adapter: mysql2
    username: <%= if $MYSQL_USERNAME then ENV['MYSQL_USERNAME'] else 'root' end %>
    password: <%= ENV['MYSQL_PASSWORD'] %>
    database: <%= ENV['MYSQL_DATABASE'] %>
