production:
    adapter: mysql2
    username: <%= if $MYSQL_USERN then ENV['MYSQL_USERN'] else 'root' end %>
    password: <%= ENV['MYSQL_PASSWORD'] %>
    database: <%= ENV['MYSQL_DATABASE'] %>
    host: <%= if $MYSQL_ADDRESS then 'localhost' else ENV['MYSQL_ADDRESS'] end %>
