development:
    adapter: mysql2
    username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
    password: <%= ENV['MYSQL_PASSWORD'] || '' %>
    database: <%= ENV['MYSQL_DATABASE'] || 'dev'%>
    host: <%= ENV['MYSQL_ADDRESS'] || 'localhost' %>
