production:
    adapter: mysql2
    username: <%= if ENV['MYSQL_USERNAME'].nil? then 'root' else ENV['MYSQL_USERNAME'] end %>
    password: <%= ENV['MYSQL_PASSWORD'] %>
    database: <%= ENV['MYSQL_DATABASE'] %>
    host: <%= if ENV['MYSQL_ADDRESS'].nil? then 'localhost' else ENV['MYSQL_ADDRESS'] end %>
