development:
    adapter: mysql2
    username: <%= ENV['MYSQ_USERNAME'] || 'root' %>
    password: <%= ENV['MYSQ_PASSWORD'] || '' %>
    database: <%= ENV['MYSQ_DATABASE'] || 'dev'%>
    host: <%= ENV['MYSQ_ADDRESS'] || 'localhost' %>
